name: Download artifact job

on:
  workflow_dispatch:
    inputs:
      your-name:
        description: Log level
        required: true
        type: string
        default: lalit

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Print dir and files
        run: |
          id
          pwd
          rm -rf
          ls -lrta
          tree .
                  
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-test-artifact
          # github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          # repository: Lalitduggal/gha
          run-id: 1

      - name: Print dir and files
        run: |
          id
          pwd
          ls -lrta
          tree .
