name: Download artifact job

on:
  workflow_dispatch:
    inputs:
      build-job-run-id:
        description: Build artifact job run id
        required: true
        type: string
        default: 12094908350

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Print dir and files
        run: |
          id
          pwd
          rm -rf
          ls -lrta
          tree .
                  
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-test-artifact
          path: my-test-artifact
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ inputs.build-job-run-id }}

      - name: Print dir and files
        run: |
          id
          pwd
          ls -lrta
          tree .
