name: Operation Stop Start job

on:
  workflow_dispatch:
    inputs:
      your-name:
        description: Log level
        required: true
        type: boolean
        default: true

jobs:
  stop:
    runs-on: ubuntu-latest
    environment: stop
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Print dir and files
        run: |
          id
          pwd
          ls -lrta
          tree .
                  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-test-artifact
          path: ./README.md
          
  start:
    runs-on: ubuntu-latest
    needs: stop
    environment: start
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Print dir and files
        run: |
          id
          pwd
          ls -lrta
          tree .
                  
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-test-artifact
          
