name: Project a

on:
  workflow_dispatch:
    inputs:
      project-a-1:
        description: project-a-1
        required: true
        type: boolean
        default: false

      project-a-2:
        description: project-a-2
        required: true
        type: boolean
        default: false

      project-a-3:
        description: project-a-3
        required: true
        type: boolean
        default: false

      project-a-4:
        description: project-a-4
        required: true
        type: boolean
        default: false
jobs:
  stop:
    runs-on: ubuntu-latest
    # environment: stop
    steps:
      - name: before file creation
        run: |
          cat > before.txt <<EOF
          lalit duggal
          praveen duggal
          savita duggal
          EOF
                  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-test-before-artifact
          path: ./before.txt
          
  start:
    runs-on: ubuntu-latest
    needs: stop
    # environment: start
    steps:
      - name: after file creation
        run: |
          cat > after.txt <<EOF
          vansh duggal
          darsh duggal
          savita mehta
          lalit kumar
          praveen duggal
          EOF

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-test-after-artifact
          path: ./after.txt

  report:
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download a Before Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-test-before-artifact

      - name: Download a After Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-test-after-artifact

      - name: compare files
        run: |
          pwd
          ls -R
          cat ./before.txt | sort > ./before_sorted.txt
          cat ./after.txt | sort > ./after_sorted.txt

          echo "Only before"
          comm -23 ./before_sorted.txt ./after_sorted.txt

          echo "Only after"
          comm -13 ./before_sorted.txt ./after_sorted.txt

          echo "both before and after"
          comm -12 ./before_sorted.txt ./after_sorted.txt

          echo "diff before and after"
          diff -y ./before_sorted.txt ./after_sorted.txt && echo "no difference" || echo "difference"

          echo "diff before and after"
          diff ./before_sorted.txt ./after_sorted.txt && echo "no difference" || echo "difference"
